### PR TITLE
STK 1.3

### PR DESCRIPTION
**Pull request by lucyllewy**
Signed-off-by: Dani Llewellyn <diddledani@ubuntu.com>

### CODE REVIEW

**Comment by Benau** [comment]
btw I recommend you patch your stk snap package so that it fix the annoying letsencrypt problem
https://github.com/supertuxkart/stk-code/issues/4635
https://github.com/supertuxkart/stk-code/commit/9bf537ab351f165555048fbc5df88193d8cd70f2

**Comment by lucyllewy** [comment]
Thanks for the prompt. I've added the patch via 0dfb277. It's building now.

**Comment by Benau** [comment]
will it promoted to stable soon instead of edge?

**Comment by lucyllewy** [comment]
I've just pushed it to stable now.

**Pull request merged**
